name: application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  http: ^1.3.0 
  provider: ^6.1.2
  dio: ^5.5.0+1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.2
  jwt_decode: ^0.3.1
  settings_ui: ^2.0.2
  kartal: ^4.1.0
  flutter_mobx: ^2.3.0
  lottie: ^3.0.0
  font_awesome_flutter: ^10.8.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.2
  mobile_scanner: ^6.0.1
  image_picker: ^1.1.2
  flutter_locales: ^3.0.4
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/loginlogo.png
  